AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
